### ISSUE TITLE
TypeError: warmup() got an unexpected keyword argument 'half'

### ISSUE THREAD

**Issue by ghost** [mohenghui/detectAuto#2]
请问发生错误该如何解决?

Fusing layers...
YOLOv5s_v6 summary: 213 layers, 7225885 parameters, 0 gradients
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\anaconda3\envs\yolov5\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "detect_auto.py", line 265, in tes06
    self.work()
  File "detect_auto.py", line 198, in work
    coordinates_list = self.run(image, model, self.device, self.half)
  File "D:\anaconda3\envs\yolov5\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect_auto.py", line 60, in run
    model.warmup(imgsz=(1, 3, *img_size), half=half)  # warmup
TypeError: warmup() got an unexpected keyword argument 'half'

**Comment by mohenghui** [comment]
已经修改，注释掉warmup就可以了

**Comment by twwinniejiang** [comment]
>

**Comment by ghost** [comment]
> 已经修改，注释掉warmup就可以了

OK, Thank you very much.
